#!/bin/sh

# reading availible pkglist-fields
fields=`man pkglist | grep "^[\t ]\+[1-9][0-9]*:[a-z]\+\($\|[\t ]\+[1-9][0-9]*:[a-z]\+\)" | sed "s/[0-9]*://g"`
pkglist="bunzip2 -c /var/db/pkg/pkglist.bz2"

$pkglist | while IFS=":" read $fields end; do
	case $srcbin in
		0|4)
		echo "b:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$bsize:$bmd5::$keyID:0:0:"
		;;
		2)
		echo "s:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$psize:$pmd5::$keyID:0:0:"
		;;
		*)
		echo "b:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$bsize:$bmd5::$keyID:0:0:"
		echo "s:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$psize:$pmd5::$keyID:0:0:"
		;;
	esac
	unset $fields
done | sed 's/·/\\:/g'
