#!/bin/sh
# spiceman - distributed package management tools
# Copyright (C) Enno Boland
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software

convertpkg () {
	fields=`man pkglist | grep "^[\t ]\+[1-9][0-9]*:[a-z]\+\($\|[\t ]\+[1-9][0-9]*:[a-z]\+\)" | sed "s/[0-9]*://g"`
	while IFS=":" read $fields end; do
		case $srcbin in
			0|4)
			echo "b:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$bsize:$bmd5::$keyID:0:0:"
			;;
			2)
			echo "s:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$psize:$pmd5::$keyID:0:0:"
			;;
			*)
			echo "b:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$bsize:$bmd5::$keyID:0:0:"
			echo "s:$pkgname:$pkgver:$pkgrel:$pkgdesc:some\://location:$useflags:$repositoy$repository:$url:$depends:$conflicts:$provides:$psize:$pmd5::$keyID:0:0:"
			;;
		esac
	done | sed 's/·/\\:/g'
}

help() {
	echo "space2spice - script to convert spaceman pkglist to spiceman packages"
	echo "usage: space2spice <indir> <outdir>"
	exit 1;
}

[ "$1" = "-h" ] && help;
[ "$#" -eq "2" ] || help;

indir=$1
outdir=$2

echo "Converting pkglist"
bunzip2 -c $indir/pkglist.bz2 | convertpkg > $outdir/packages

echo "Converting installed"
bunzip2 -c $indir/installed.bz2 | convertpkg > $outdir/installed

